---
title: "HedgeFollow Star Hedgefund Portolio"
output: 
    flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll

---

```{r setup, include=FALSE}
library(flexdashboard)
setwd("D:/wooseok/0.Quantitative Applied Economics/2.경제데이터분석 (최재성 교수님)/기말프로젝트 과제/최종")
library(dplyr)
library(stringr)
library(httr)
library(XML)
library(jsonlite)
library(readxl)
library(writexl)
library(RSelenium)
library(rvest)
library(gsubfn)
library(readr)
library(formattable)
library(lubridate)
library(knitr)
library(kableExtra)
library(dplyr)
library(httr)
library(rvest)
library(xml2)
library(stringr)

Stack4_filtered <- read_excel("Hedgefollow(Masterfile).xlsx")

```

Column {data-width=650}

-----------------------------------------------------------------------

```{r}
kable(Stack4_filtered) %>%
  kable_styling("striped", full_width = F) %>%
  scroll_box(width = "100%", height = "200px")
```

Column {.tabset .tabset-fade}

-----------------------------------------------------------------------
  
### Warren Buffet Top Stocks

```{r}
#warrenbuffet top stocks

Warrenonly<- Stack4_filtered[grepl("Warren Buffett", Stack4_filtered$fundmanager.list),]

# 펀드매니져별 보유 종목 및 보유 금액 

Warrenvalue <- Warrenonly[,10]
Warrencompany <- Warrenonly[,3]


#펀드매니져 별로 파이차트 그리기

pie(Warrenvalue ,main="Warren Buffet Top Holding Stocks", col=rainbow(length(Warrenvalue)), labels=Warrencompany) 



```

-----------------------------------------------------------------------

### Carl Icahn Top Stocks

```{r}
#Carl Icahn top stocks

Carlonly<- Stack4_filtered[grepl("Carl Icahn", Stack4_filtered$fundmanager.list),]

  
Carlvalue <- Carlonly[,10]
Carlcompany <- Carlonly[,3]
  
pie(Carlvalue ,main="Carl Icahn Top Holding Stocks",col=rainbow(length(Carlvalue )), labels=Carlcompany)  


```

### Michael Burry top stocks

```{r}
#Michael Burry top stocks

Michaelonly<- Stack4_filtered[grepl("Michael Burry", Stack4_filtered$fundmanager.list),]

Michaelvalue <- Michaelonly[,10]
Michaelcompany <- Michaelonly[,3]

pie(Michaelvalue ,main="Michael Burry Top Holding Stocks",col=rainbow(length(Michaelvalue)), labels=Michaelcompany) 


```

### George Soros Top Stocks

```{r}
#George Soros top stocks

Georgeonly<- Stack4_filtered[grepl("George Soros", Stack4_filtered$fundmanager.list),]

  
Georgevalue <- Georgeonly[,10]
Georgecompany <- Georgeonly[,3]

pie(Georgevalue ,main="George Soros Top Holding Stocks",col=rainbow(length(Georgevalue)), labels=Georgecompany) 


```

### Bill Ackman Top Stocks

```{r}
#Bill Ackman top stocks

Billonly<- Stack4_filtered[grepl("Bill Ackman", Stack4_filtered$fundmanager.list),]

Billvalue <- Billonly[,10]
Billcompany <- Billonly[,3]

pie(Billvalue,main="Bill Ackman Top Holding Stocks",col=rainbow(length(Billvalue)), labels=Billcompany) 

```

### John Paulson  Top Stocks

```{r}
#John Paulson  top stocks

Johnonly<- Stack4_filtered[grepl("John Paulson", Stack4_filtered$fundmanager.list),]

Johnvalue<- Johnonly[,10]
Johncompany <- Johnonly[,3]

pie(Johnvalue,main="John Paulson Top Holding Stocks",col=rainbow(length(Johnvalue)), labels=Johncompany) 

```
### David Tepper  Top Stocks

```{r}
#David Tepper top stocks

Davidonly<- Stack4_filtered[grepl("David Tepper ", Stack4_filtered$fundmanager.list),]

Davidvalue<- Davidonly[,10]
Davidcompany <- Davidonly[,3]

pie(Davidvalue,main="David Tepper Top Holding Stocks",col=rainbow(length(Davidvalue)), labels=Davidcompany)

```
### Daniel Loeb Top Stocks

```{r}
#Daniel Loeb  

Danielonly<- Stack4_filtered[grepl("Daniel Loeb", Stack4_filtered$fundmanager.list),]

Danielvalue<- Danielonly[,10]
Danielcompany <-Danielonly[,3] 

pie(Danielvalue,main="Daniel Loeb Top Holding Stocks",col=rainbow(length(Danielvalue)), labels=Danielcompany)
```